FROM registry.cn-hangzhou.aliyuncs.com/knative-sample/golang:1.12.9 as builder

# Copy local code to the container image.
WORKDIR /go/src/github.com/knative-sample/cloud-native-go-weather
COPY . .
# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o detail github.com/knative-sample/cloud-native-go-weather/cmd/detail

FROM registry.cn-beijing.aliyuncs.com/knative-sample/centos:7.6.1810
COPY --from=builder /go/src/github.com/knative-sample/cloud-native-go-weather/detail /detail

# Run the web service on container startup.
CMD ["/detail"]
