FROM registry.cn-hangzhou.aliyuncs.com/knative-sample/golang:1.12.9 as builder

# Copy local code to the container image.
WORKDIR /go/src/github.com/knative-sample/cloud-native-go-weather
COPY . .
# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o weather github.com/knative-sample/cloud-native-go-weather/cmd/weather

FROM registry.cn-beijing.aliyuncs.com/knative-sample/centos:7.6.1810
COPY --from=builder /go/src/github.com/knative-sample/cloud-native-go-weather/weather /weather
COPY static/ /var/html/
# Run the web service on container startup.
CMD ["/weather"]
